"""
Email sender — supports SendGrid, SMTP, or logging-only fallback.

Configure via .env:
  EMAIL_PROVIDER=sendgrid   → uses SENDGRID_API_KEY
  EMAIL_PROVIDER=smtp       → uses SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD
  EMAIL_PROVIDER=none       → logs token to console (dev default)
"""
from __future__ import annotations
import os
import logging

log = logging.getLogger("zoiko.email")

EMAIL_PROVIDER = os.getenv("EMAIL_PROVIDER", "none").lower().strip()
EMAIL_FROM     = os.getenv("EMAIL_FROM", "noreply@zoikotech.com")
APP_URL        = os.getenv("APP_URL", "http://localhost:5173")


def send_password_reset(to_email: str, raw_token: str, expires_at: str) -> None:
    link = f"{APP_URL}/login?flow=recovery&token={raw_token}"
    subject = "Reset your Zoiko password"
    body = f"""Hello,

You requested a password reset for your Zoiko account.

Click the link below to reset your password (expires {expires_at}):
{link}

If you did not request this, ignore this email.

— Zoiko AI Logistics
"""
    _send(to_email, subject, body, link)
    log.info("Password reset email sent to %s (provider=%s)", to_email, EMAIL_PROVIDER)


def send_invitation(to_email: str, invited_by: str, role: str, raw_token: str, expires_at: str) -> None:
    link = f"{APP_URL}/login?flow=invite&token={raw_token}"
    subject = f"You're invited to join Zoiko as {role.title()}"
    body = f"""Hello,

{invited_by} has invited you to join Zoiko AI Logistics as {role.title()}.

Click the link below to accept your invitation and set your password (expires {expires_at}):
{link}

— Zoiko AI Logistics
"""
    _send(to_email, subject, body, link)
    log.info("Invitation email sent to %s as %s (provider=%s)", to_email, role, EMAIL_PROVIDER)


def send_dispute_letter(
    to_email: str,
    carrier: str,
    case_id: str,
    letter_text: str,
    overcharge: float,
    currency: str,
    from_name: str = "Zoiko AI Logistics",
) -> None:
    """Send the AI-generated dispute letter to the carrier's email."""
    subject = f"Freight Overcharge Dispute — Case {case_id[:8].upper()} | {carrier}"
    sym = "₹" if currency == "INR" else ("$" if currency == "USD" else currency + " ")

    html = f"""
    <div style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;color:#1e293b">
      <div style="background:#1e3a8a;padding:20px 28px;border-radius:8px 8px 0 0">
        <span style="color:white;font-size:22px;font-weight:800">ZOIKO</span>
        <span style="color:#60a5fa;font-size:22px;font-weight:800">AI</span>
        <span style="color:#94a3b8;font-size:12px;margin-left:12px">Freight Audit Platform</span>
      </div>
      <div style="border:1px solid #e2e8f0;border-top:none;border-radius:0 0 8px 8px;padding:28px">
        <div style="background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:12px 16px;margin-bottom:20px">
          <strong style="color:#dc2626">Formal Dispute Notice</strong>
          <span style="color:#64748b;font-size:12px;margin-left:8px">Case: {case_id[:8].upper()} | Overcharge: {sym}{overcharge:,.2f} {currency}</span>
        </div>
        <pre style="font-family:Arial,sans-serif;white-space:pre-wrap;font-size:13px;line-height:1.7;color:#1e293b">{letter_text}</pre>
        <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0"/>
        <p style="font-size:11px;color:#94a3b8">
          This letter was generated by <strong>Zoiko AI Logistics</strong> freight audit platform.
          Case reference: <code>{case_id}</code> | Cryptographic ACR available on request.
        </p>
      </div>
    </div>
    """

    _send_html(to_email, subject, letter_text, html)
    log.info("Dispute letter sent to %s for case %s (provider=%s)", to_email, case_id, EMAIL_PROVIDER)


def _send(to: str, subject: str, body: str, link: str) -> None:
    if EMAIL_PROVIDER == "sendgrid":
        _send_sendgrid(to, subject, body)
    elif EMAIL_PROVIDER == "smtp":
        _send_smtp(to, subject, body)
    else:
        # Dev fallback — log the link so admin can copy it manually
        log.info(
            "EMAIL (provider=none) | To: %s | Subject: %s | Link: %s",
            to, subject, link,
        )
        print(f"\n{'='*60}\nEMAIL TO: {to}\nSUBJECT: {subject}\nLINK: {link}\n{'='*60}\n")


def _send_html(to: str, subject: str, plain: str, html: str) -> None:
    """Send email with HTML body (falls back to plain text)."""
    if EMAIL_PROVIDER == "sendgrid":
        _send_sendgrid(to, subject, plain, html)
    elif EMAIL_PROVIDER == "smtp":
        _send_smtp(to, subject, plain)
    else:
        print(f"\n{'='*60}\nEMAIL TO: {to}\nSUBJECT: {subject}\n{'='*60}\n{plain}\n")


def _send_sendgrid(to: str, subject: str, body: str, html: str = "") -> None:
    api_key  = os.getenv("SENDGRID_API_KEY", "")
    sandbox  = os.getenv("SENDGRID_SANDBOX", "true").lower() == "true"
    if not api_key:
        raise RuntimeError("SENDGRID_API_KEY not set")
    try:
        import sendgrid
        from sendgrid.helpers.mail import Mail, MailSettings, SandBoxMode
        sg   = sendgrid.SendGridAPIClient(api_key=api_key)
        mail = Mail(
            from_email        = EMAIL_FROM,
            to_emails         = to,
            subject           = subject,
            plain_text_content= body,
            html_content      = html or body,
        )
        # Sandbox mode — email is validated but NOT delivered (safe for testing)
        if sandbox:
            mail.mail_settings = MailSettings()
            mail.mail_settings.sandbox_mode = SandBoxMode(enable=True)
            log.info("SendGrid SANDBOX mode — email validated but not delivered")
        resp = sg.send(mail)
        log.info("SendGrid response: %s (sandbox=%s)", resp.status_code, sandbox)
    except ImportError:
        raise RuntimeError("sendgrid package not installed. Run: pip install sendgrid")


def _send_smtp(to: str, subject: str, body: str) -> None:
    import smtplib
    from email.mime.text import MIMEText
    host     = os.getenv("SMTP_HOST", "")
    port     = int(os.getenv("SMTP_PORT", "587"))
    user     = os.getenv("SMTP_USER", "")
    password = os.getenv("SMTP_PASSWORD", "")
    if not host:
        raise RuntimeError("SMTP_HOST not set")
    msg = MIMEText(body)
    msg["Subject"] = subject
    msg["From"]    = EMAIL_FROM
    msg["To"]      = to
    with smtplib.SMTP(host, port) as server:
        server.starttls()
        if user:
            server.login(user, password)
        server.sendmail(EMAIL_FROM, [to], msg.as_string())
